# Builder stage
FROM node:14.15.5-alpine3.10 AS builder

WORKDIR /usr/app

COPY package.json .

COPY yarn.lock .

RUN yarn install

COPY . .

RUN yarn build

# Serve production build using nginx
FROM nginx:1.19.8-alpine

COPY --from=builder /usr/app/build /usr/share/nginx/html

COPY --from=builder /usr/app/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
